directive @system_token(
  portalCapa: [PortalCapability!] = []
) repeatable on OBJECT | FIELD_DEFINITION

directive @platform_token repeatable on OBJECT | FIELD_DEFINITION

directive @auth(
  portalCapa: [PortalCapability] = []
  orgaCapa: [OrganizationCapability] = []
) repeatable on OBJECT | FIELD_DEFINITION

enum PortalCapability {
  BYPASS
  READ_TRIALS
  MODIFY_TRIALS
  MODIFY_TRIALS_QUOTA
  MODIFY_COMPETITORS
  MODIFY_SERVICE_METADATA
  MANAGE_DEPLOYMENT
  MANAGE_CONNECTORS_INGESTIONS
  MANAGE_MANIFEST_INGESTIONS
  GENERATE_MANIFEST
  READ_SAAS_METRICS
}

enum OrganizationCapability {
  ADMINISTRATE_ORGANIZATION
  MANAGE_ACCESS
  MANAGE_SUBSCRIPTION
  MANAGE_PLATFORM_REGISTRATION
}

directive @service_capa(
  requires: [ServiceRestriction] = []
) repeatable on OBJECT | FIELD_DEFINITION

enum ServiceRestriction {
  ACCESS
  ACCESS_USER
  MANAGE_ACCESS
  UPLOAD
  DELETE
  UPSERT
}

interface Node {
  id: ID!
}

enum OrderingMode {
  asc
  desc
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type MergeEvent implements Node {
  id: ID!
  from: ID!
  target: ID!
}

type Query {
  node(id: ID!): Node @auth
}
