tls_issuer: le-staging
ingressClass: nginx
xtmhub:
  node_env: "production"
  api:
    devUsers: ""
    repository: "portal-api-prod"
    replicas: 1
    admin:
      email: ""
      password: ""
    env:
      OIDC_ISSUER: ""
      OIDC_CLIENT_ID: ""
      OIDC_REDIRECT_URIS: ""
      OIDC_LOGOUT_CALLBACK_URL: ""
      MINIO_USE_SSL: "false"
      MINIO_PORT: 80
      MINIO_ENDPOINT: minio
      PORTAL_COOKIE_NAME: ""
      PORTAL_COOKIE_SECRET: ""
    resources:
      requests:
        cpu: "64m"
        memory: 128Mi
      limits:
        memory: 8Gi
    secret:
      OIDC_CLIENT_SECRET: ""
    livenessProbe: {}
    elasticsearchCAFromSecret:
      enabled: true
      CASecretName: "elasticsearch-es-http-ca-internal"
  front:
    repository: "portal-front-prod"
    replicas: 1
    livenessProbe: {}
    resources:
      requests:
        cpu: "128m"
        memory: 100Mi
      limits:
        memory: 4Gi
  imagePullSecrets: []
  labels:
    environment: dev
  version: master
  host: localhost
postgres:
  version: "17.2"
  replicas: 2
  username: xtmhub
  storage:
    size: 10Gi
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      memory: 8Gi
  backup:
    enabled: false
    retentionPolicy: 7d
    serverName: postgresql
    s3BucketName: "postgres"
    endpointURL: "https://s3.amazonaws.com"
    s3Credentials:
      accessKeyId:
        name: backup-s3-cred
        key: accessKey
      secretAccessKey:
        name: backup-s3-cred
        key: secretKey
  spec:
    bootstrap:
      initdb:
        database: xtmhub
        owner: xtmhub
    # externalClusters:
    # plugins:
  pgadmin:
    whitelistSourceRange: "149.88.28.168/32,10.0.0.0/8"
    version: "8.14"
    username: xthmhub@filigran.io
    password: "CHANGEME--q5Y6NbtbeIu3qyjk0iPthl2hCUkAmB--CHANGEME"
minio:
  image:
    repository: pgsty/silo
    tag: latest
    pullPolicy: IfNotPresent
  ingressWhitelistSourceRange: "149.88.28.168/32,10.0.0.0/8"
  resources:
    requests:
      cpu: "256m"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "8Gi"
  storage:
    diskSize: 10Gi
    diskCount: 2
  server:
    count: 3
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                v1.min.io/tenant: xtmhub-minio
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchLabels:
                v1.min.io/tenant: xtmhub-minio
            topologyKey: rack
elasticsearch:
  enabled: true
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
            topologyKey: kubernetes.io/hostname
  clusterName: "elasticsearch"
  priorityClassName: ""
  secretNameSuffix: -es-elastic-user
  image:
    repository: elasticsearch
    tag: 8.18.3
  replicas: 2
  storage:
    size: 5Gi
    classname: openebs-lvmpv
  nodeSelector: {}
  java_opts: -Xms2g -Xmx2g -Xlog:disable -Xlog:all=warning:stderr:utctime,level,tags -Xlog:gc=debug:stderr:utctime
  allow_mmap: true
  resources:
    requests:
      memory: 3Gi
      cpu: "256m"
    limits:
      memory: 4Gi
  plugin_prometheus_enabled: true
  reindexRemote:
    enabled: false
    serviceName: opensearch-cluster-master
    port: "9200"
  externalMinioRestore:
    enabled: false
    # Used to define which namespace ES will connect as a snapshot repository. Required
    # namespace: customer-example-minio
    port: 9000
  ingress:
    enabled: false
    host: localhost
    annotations: {}
kibana:
  enabled: true
  priorityClassName: ""
  ingress:
    enabled: true
    annotations: {}
