type RolePortal implements Node {
  id: ID!
  name: String!
  capabilities: [Capability]
}

type SSOGroupRolePortal {
  ssoGroup: String!
  rolePortal: RolePortal!
}

input AddSSOGroupRolePortalInput {
  ssoGroup: String!
  rolePortal: String!
  capabilities: [PortalCapability!]!
}

extend type Query {
  ssoGroupRolePortals: [SSOGroupRolePortal!]! @auth(portalCapa: BYPASS)
}

extend type Mutation {
  addSSOGroupRolePortal(
    input: AddSSOGroupRolePortalInput!
  ): SSOGroupRolePortal! @auth(portalCapa: BYPASS)
}
