input ManifestFragmentInput {
  id: String!
  title: String!
  slug: String!
  description: String!
  short_description: String!
  logo: String!
  use_cases: [String!]!
  verified: Boolean
  last_verified_date: String
  subscription_link: String
  source_code: String!
  manager_supported: Boolean!
  min_version: String!
  version: String!
  image_name: String!
  image_type: String!
  platform: String!
  integration_type: String!
  additional_properties: JSON!
  config_schema: JSON!
  license_type: LicenseType
  contact: String
  solution_categories: [String!]!
  coverage: IntegrationCoverageInput
}

type Mutation {
  ingestManifestFragments(
    manifestFragments: [ManifestFragmentInput!]!
  ): Success! @system_token(portalCapa: [MANAGE_MANIFEST_INGESTIONS])
}
