scalar NewsFeedItemId

enum NewsFeedItemType {
  RESOURCE_CUSTOM_DASHBOARD
  RESOURCE_PLAYBOOK
  RESOURCE_CUSTOM_VIEW
  RESOURCE_INTEGRATION
}

enum NewsFeedItemMetadataKey {
  url_path
  document_id
}

type NewsFeedItemMetadata {
  key: NewsFeedItemMetadataKey!
  value: String
}

# Warning ! Used by OpenCTI, should be used by XTM Hub because of ID conflicts
type ProvisionedNewsFeedItem implements Node {
  id: ID!
  is_deleted: Boolean!
  title: String!
  type: NewsFeedItemType!
  tags: [String!]!
  metadata: [NewsFeedItemMetadata!]!
  creation_date: Date!
}

type ConsumeProvisionedNewsFeedItemsResponse {
  news_feed_items: [ProvisionedNewsFeedItem!]!
  available_news_feed_types: [NewsFeedItemType!]!
}

type NewsFeedItem implements Node {
  id: ID!
  title: String!
  type: NewsFeedItemType!
  creation_date: Date!
  tags: [String!]!
  is_deleted: Boolean!
  metadata: [NewsFeedItemMetadata!]!
}

type NewsFeedItemEdge {
  cursor: String!
  node: NewsFeedItem!
}

type NewsFeedItemConnection {
  totalCount: Int!
  edges: [NewsFeedItemEdge!]!
  pageInfo: PageInfo!
}

extend type Query {
  newsFeedItems(first: Int!, after: ID): NewsFeedItemConnection!
    @auth(portalCapa: BYPASS)
}

type Mutation {
  # Warning ! Used by OpenCTI
  consumeProvisionedNewsFeedItems: ConsumeProvisionedNewsFeedItemsResponse!
    @platform_token
  deleteNewsFeedItem(id: NewsFeedItemId!): Boolean! @auth(portalCapa: BYPASS)
}
