compressionLevel: mixed

defaultSemverRangePrefix: ""

catalog:
  "@eslint/js": "10.0.1"
  "@graphql-codegen/cli": "5.0.7"
  "@graphql-codegen/typescript": "4.1.6"
  "@types/node": "24.13.3"
  "@vitest/coverage-v8": "4.1.11"
  concurrently: "9.2.4"
  eslint: "10.9.1"
  eslint-config-prettier: "10.1.8"
  globals: "17.12.0"
  graphql: "16.14.2"
  graphql-sse: "2.6.1"
  husky: "9.1.7"
  knex: "3.3.0"
  lint-staged: "17.3.0"
  monocart-reporter: "2.12.6"
  pg: "8.23.0"
  prettier: "3.9.6"
  prettier-plugin-organize-imports: "4.3.0"
  react: "19.2.8"
  react-dom: "19.2.8"
  tsx: "4.23.13"
  typescript: "6.0.3"
  typescript-eslint: "8.68.0"
  uuid: "14.0.2"
  vite: "8.2.2"
  vitest: "4.1.11"
  zod: "4.4.3"

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "@filigran/*"
