scalar DocumentId

enum DocumentSourceType {
  external
  internal
}

enum DocumentImageType {
  logo
  image
}

enum LicenseType {
  Commercial
  Free
}

enum DocumentMetadataKeyCode {
  feed_url
  integration_type
  last_verified_date
  datasheet_url
  blogpost_url
  demo_url
  product_version
  vendor_url
  github_url
  container_image
  verified
  source_code
  subscription_link
  manager_supported
  playbook_supported
  image_name
  image_type
  minimum_deployable_version
  minimum_deployable_version_padded
  version_padded
  additional_properties
  config_schema
  manifest_fragment_id
  entity_types
  solution_categories
  license_type
  contact
}

type ShareableResource {
  id: ID!
  file_name: String!
  created_at: Date!
  name: String
  description: String
  download_number: Int
  active: Boolean!
  source_type: DocumentSourceType!
  image_type: DocumentImageType
}

enum DocumentOrdering {
  file_name
  description
  created_at
  updated_at
  download_number
  name
}

type PublicDocumentSlugInfo {
  slug: String
  created_at: Date!
  updated_at: Date
}

"""
/!\ WARNING Do not use this type.
It exists only to cover cases where we failed to map to a specific Document.
"""
type DefaultDocument implements Node & Document {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String
  short_description: String
  description: String
  file_name: String @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String
  use_cases: [UseCase!]
  service_instance_id: ServiceInstanceId
  service_instance: ServiceInstance @auth
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResource!]
}

interface Document implements Node {
  id: ID!
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String
  short_description: String
  description: String
  file_name: String @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String
  use_cases: [UseCase!]
  service_instance_id: ServiceInstanceId
  service_instance: ServiceInstance @auth
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResource!]
}

input DocumentMetadata {
  key: DocumentMetadataKeyCode!
  value: String!
}

input CreateDocumentInput {
  name: String!
  slug: String!
  short_description: String!
  description: String!
  active: Boolean!
  use_cases: [UseCaseId!]!
  solution_categories: [SolutionCategoryId!]!
  license_type: LicenseType
  entity_types: [String!]
  uploader_id: UserId!
}

input UpdateDocumentInput {
  name: String
  short_description: String
  description: String
  active: Boolean
  use_cases: [UseCaseId!]
  solution_categories: [SolutionCategoryId!]
  license_type: LicenseType
  entity_types: [String!]
  uploader_organization_id: OrganizationId
  uploader_id: UserId
}

type DocumentEdge {
  cursor: String!
  node: Document!
}

type DocumentConnection {
  totalCount: Int!
  edges: [DocumentEdge!]!
  pageInfo: PageInfo!
}

type Mutation {
  createDocument(
    input: CreateDocumentInput!
    metadata: [DocumentMetadata!]!
    serviceInstanceId: ServiceInstanceId!
    sourceDocument: Upload
    logo: Upload
    images: [Upload!]
  ): Document! @auth @service_capa(requires: [UPLOAD])
  updateDocument(
    documentId: DocumentId!
    input: UpdateDocumentInput!
    metadata: [DocumentMetadata!]!
    serviceInstanceId: ServiceInstanceId!
    sourceDocument: Upload
    logo: Upload
    images: [Upload!]
    existingImageIds: [DocumentId!]
  ): Document! @auth @service_capa(requires: [UPLOAD])
  deleteDocument(
    documentId: DocumentId!
    service_instance_id: ServiceInstanceId!
    forceDelete: Boolean
  ): Document! @auth @service_capa(requires: [DELETE])
  incrementShareNumberDocument(documentId: DocumentId!): Document!
}

type Query {
  documentExists(
    documentName: String
    service_instance_id: ServiceInstanceId!
  ): Boolean @auth @service_capa(requires: [UPLOAD])
  publicDocuments(
    slug: String!
    first: Int!
    after: ID
    orderBy: DocumentOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    logicalFilters: LogicalFilterInput
    serviceInstanceId: ServiceInstanceId!
  ): DocumentConnection!
  publicDocumentsByServiceSlug(serviceInstanceSlug: String!): [Document!]!
  publicDocumentSlugsByServiceSlug(
    serviceInstanceSlug: String!
  ): [PublicDocumentSlugInfo!]!
  publicDocumentBySlug(
    serviceInstanceId: ServiceInstanceId!
    slug: String!
  ): Document
  documents(
    first: Int!
    after: ID
    orderBy: DocumentOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    logicalFilters: LogicalFilterInput
    serviceInstanceId: ServiceInstanceId!
    parentsOnly: Boolean
  ): DocumentConnection! @auth
  document(
    documentId: DocumentId!
    serviceInstanceId: ServiceInstanceId!
  ): Document @auth
  mostDeployedDocuments(
    limit: Int!
    platformIdentifiers: [PlatformIdentifier!]
  ): [Document!]!
  newestDocuments(
    limit: Int!
    platformIdentifiers: [PlatformIdentifier!]
  ): [Document!]!
  lastDeployedOverview(
    limit: Int!
    serviceInstanceId: ServiceInstanceId!
  ): LastDeployedOverview! @auth
}

type DeployedResource {
  document: Document!
  deployedAt: Date!
  deployedBy: User
}

type LastDeployedOverview {
  resources: [DeployedResource!]!
}
