scalar UserId

enum UserOrdering {
  email
  first_name
  last_name
  disabled
  country
  last_login
}

type Capability implements Node {
  id: ID!
  name: PortalCapability!
}

type OrganizationCapabilities implements Node {
  id: ID!
  organization: Organization!
  capabilities: [OrganizationCapability!]
}

type User implements Node {
  id: ID!
  email: String!
  first_name: String
  last_name: String
  picture: String
  country: String
  selected_language: String
  disabled: Boolean
  selected_organization_id: OrganizationId
  organizations: [Organization!]
  organization_capabilities: [OrganizationCapabilities!]
  capabilities: [Capability!]
  roles_portal: [RolePortal!]
  selected_org_capabilities: [OrganizationCapability!]
  last_login: Date
  pending_organization_id: OrganizationId
}

type UserEdge {
  cursor: String!
  node: User!
}

type UserConnection {
  totalCount: Int!
  edges: [UserEdge!]!
  pageInfo: PageInfo!
}

input UsersWithCapabilitiesInOrganizationInput {
  organizationId: OrganizationId!
  capabilities: [OrganizationCapability!]!
}

type Query {
  me: User
  usersWithCapabilitiesInOrganization(
    input: UsersWithCapabilitiesInOrganizationInput!
  ): [User!]!
  users(
    first: Int!
    after: ID
    orderBy: UserOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    filters: [Filter!]
  ): UserConnection! @auth
  pendingUsers(
    first: Int!
    after: ID
    orderBy: UserOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    filters: [Filter!]
  ): UserConnection! @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
}

input AdminEditUserInput {
  disabled: Boolean
  first_name: String
  last_name: String
  email: String
  organization_capabilities: [OrganizationCapabilitiesInput!]
}

input EditUserCapabilitiesInput {
  capabilities: [String!]
}

input EditMeUserInput {
  first_name: String
  last_name: String
  country: String
  selected_language: String
}

input OrganizationCapabilitiesInput {
  organization_id: OrganizationId!
  capabilities: [String!]
}

input AddUserInput {
  email: String!
  password: String
  capabilities: [String!]
}
input AdminAddUserInput {
  email: String!
  first_name: String
  last_name: String
  password: String
  organization_capabilities: [OrganizationCapabilitiesInput!]
}

input BulkPendingUserFromOrganizationInput {
  ids: [UserId!]
  searchTerm: String
  filters: [Filter!]
  excludedIds: [UserId!]
}

type Mutation {
  # Admin
  adminAddUser(input: AdminAddUserInput!): User @auth(portalCapa: [BYPASS])
  adminEditUser(id: ID!, input: AdminEditUserInput!): User!
    @auth(portalCapa: [BYPASS])
  deleteUser(id: ID!): User! @auth(portalCapa: [BYPASS])

  # Management
  addUser(input: AddUserInput!): User
    @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  editUserCapabilities(id: ID!, input: EditUserCapabilitiesInput!): User!
    @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  changeSelectedOrganization(organization_id: OrganizationId!): User @auth
  bulkRemovePendingUserFromOrganization(
    input: BulkPendingUserFromOrganizationInput!
  ): Success @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  bulkAcceptPendingUserInOrganization(
    input: BulkPendingUserFromOrganizationInput!
  ): Success @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  acceptPendingUserInOrganization(
    user_id: UserId!
    organization_id: OrganizationId!
  ): User @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  removePendingUserFromOrganization(
    user_id: UserId!
    organization_id: OrganizationId!
  ): User @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  removeUserFromOrganization(
    user_id: UserId!
    organization_id: OrganizationId!
  ): User @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])

  # Profile
  editMeUser(input: EditMeUserInput!): User! @auth
  uploadUserPicture(document: Upload!): User! @auth
  resetPassword: Success! @auth
  requestTransferPersonalSpace(new_email: String!): Success! @auth
  transferPersonalSpace(requestId: ID!): Success! @auth

  # Login
  login(email: String!, password: String): User
  logout: ID! @auth

  # Contact
  ############ USED IN OpenCTI ############ DO NOT RENAME/REMOVE
  contactUs(
    message: String
    platformId: ID
    platformIdentifier: PlatformIdentifier
    ############ XTM Hub internal only ############
    deploymentRequestType: DeploymentRequestDeploymentType
  ): Success!
}

type UserSubscription {
  add: User
  edit: User
  delete: User
  merge: MergeEvent
}

type MeUserSubscription {
  edit: User
  delete: User
}

type UserPendingSubscription {
  delete: User
  invalidate: OrganizationRef
}

type Subscription {
  User(organizationId: ID): UserSubscription
    @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
  MeUser: MeUserSubscription @auth
  UserPending(organizationId: ID!): UserPendingSubscription
    @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_ACCESS])
}
