enum Timeline {
  now
  next
  under_consideration
  finished
}
enum EditionType {
  community_edition
  enterprise_edition
  partial_ee
}

enum EpicType {
  other
  integration
}

type Epic implements Node {
  id: ID!
  title: String!
  short_description: String!
  description: String!
  edition_type: EditionType!
  active: Boolean!
  product: [FiligranProduct!]!
  slack_link: String
  timeline: Timeline!
  epic_type: EpicType!
  document: Document
  document_id: DocumentId
  uploader_id: String!
  updater_id: String
  created_at: Date!
  updated_at: Date
}

input CreateEpicInput {
  title: String!
  short_description: String!
  description: String!
  edition_type: EditionType!
  active: Boolean
  product: [FiligranProduct!]!
  slack_link: String
  timeline: Timeline!
  is_integration: Boolean
  illustration_document: Upload
}

input UpdateEpicInput {
  title: String
  short_description: String
  description: String
  edition_type: EditionType!
  active: Boolean
  product: [FiligranProduct!]
  slack_link: String
  timeline: Timeline
  is_integration: Boolean
  illustration_document: Upload
}

type EpicCountPerTimeline {
  timeline: Timeline!
  count: Int!
}

type EpicEdge {
  cursor: String!
  node: Epic!
}
type EpicConnection {
  totalCount: Int!
  edges: [EpicEdge!]!
  pageInfo: PageInfo!
}
enum EpicOrdering {
  title
}
type Query {
  epics(
    first: Int!
    after: ID
    orderBy: EpicOrdering!
    orderMode: OrderingMode!
    searchTerm: String
  ): EpicConnection
  countEpicsPerTimeline: [EpicCountPerTimeline!]!
}

type Mutation {
  createEpic(input: CreateEpicInput!, document: [Upload!]): Epic! @auth
  updateEpic(id: ID!, input: UpdateEpicInput!, document: [Upload!]): Epic! @auth
  deleteEpic(id: ID!): Epic @auth
}
