services:
  frontend:
    container_name: frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: filigran/portal-front:${IMAGE_TAGS}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://frontend:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - SERVER_HTTP_API=http://backend:4001

  frontend-test:
    container_name: frontend-test
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: filigran/portal-front-test:${IMAGE_TAGS}
    environment:
      - SERVER_HTTP_API=http://backend:4001
    volumes:
      - "./coverage:/app/apps/frontend/coverage"
  backend-test:
    container_name: backend-test
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: filigran/portal-api-test:${IMAGE_TAGS}
    depends_on:
      portal-postgres:
        condition: service_healthy
      portal-minio:
        condition: service_healthy
    environment:
      - DATABASE_HOST=portal-postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=portal
      - DATABASE_BASE=postgres
      - DATABASE_PASSWORD=portal-password
      - ADMIN_EMAIL=admin@filigran.io
      - ADMIN_PASSWORD=admin
      - NODE_ENV=development
      - MINIO_BUCKET_NAME=xtmhubbucket
      - MINIO_ENDPOINT=portal-minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=portal
      - MINIO_SECRET_KEY=changeme
      - MINIO_USE_SSL=false
      - PORTAL_COOKIE_NAME=cloud-portal
      - PORTAL_COOKIE_SECRET=XR4MFizbXn09doSZ
    volumes:
      - "./coverage:/app/apps/backend/coverage"
  backend:
    container_name: backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: filigran/portal-api:${IMAGE_TAGS}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://backend:4001/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      portal-postgres:
        condition: service_healthy
      portal-minio:
        condition: service_healthy
      portal-elasticsearch:
        condition: service_healthy
    environment:
      - DATABASE_HOST=portal-postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=portal
      - DATABASE_BASE=test_database
      - DATABASE_PASSWORD=portal-password
      - ADMIN_EMAIL=admin@filigran.io
      - ADMIN_PASSWORD=admin
      - DATA_SEEDING=true
      - MINIO_BUCKET_NAME=xtmhubbucket
      - MINIO_ENDPOINT=portal-minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=portal
      - MINIO_SECRET_KEY=changeme
      - MINIO_USE_SSL=false
      - NODE_ENV=development
      - VITEST_MODE=true
      - START_DEV_SERVER=true
      - ELASTIC_HOST=portal-elasticsearch
      - ELASTIC_PORT=9200
      - BASE_URL_FRONT=http://frontend:3000
      - PORTAL_COOKIE_NAME=cloud-portal
      - PORTAL_COOKIE_SECRET=XR4MFizbXn09doSZ

  portal-postgres:
    container_name: portal-postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal-password
      - POSTGRES_DB=test_database
      - PGDATA=/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "test_database"]
      interval: 10s
      timeout: 5s
      retries: 10

  portal-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.3
    container_name: portal-elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  portal-minio:
    container_name: portal-minio
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: "pgsty/silo:latest"
    environment:
      MINIO_ROOT_USER: portal
      MINIO_ROOT_PASSWORD: changeme
    command: "minio server /data/minio"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 10

  e2e:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: filigran/portal-e2e-tests:${IMAGE_TAGS}
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
      portal-minio:
        condition: service_healthy
    environment:
      - E2E_BASE_URL=http://frontend:3000
      - E2E_API_URL=http://backend:4001
      - POSTGRES_USER=portal
      - DATABASE_HOST=portal-postgres
      - POSTGRES_DB=test_database
      - POSTGRES_PASSWORD=portal-password
      - DATABASE_PORT=5432
      - TEAMS_WEBHOOK_E2E=${TEAMS_WEBHOOK_E2E}
      - MIGRATIONS_PATH=./migrations
      - SEEDS_PATH=./seeds
      - GITHUB_PR_NUMBER=${GITHUB_PR_NUMBER}
      - GITHUB_PR_TITLE=${GITHUB_PR_TITLE}
      - GITHUB_RUN_ID=${GITHUB_RUN_ID}
      - SESSION_STORE_TYPE=memory
