// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { Locale } from '../../../__generated__/resolvers-types';
import type { UserId } from './User';

/** Identifier type for public.ContentTranslation */
export type ContentTranslationKey = string & { __brand: 'public.ContentTranslation' };

/** Identifier type for public.ContentTranslation */
export type ContentTranslationLocale = string & { __brand: 'public.ContentTranslation' };

/** Represents the table public.ContentTranslation */
export default interface ContentTranslation {
  key: ContentTranslationKey;

  locale: Locale;

  value: string;

  updated_at: Date;

  updater_id: UserId | null;
}

/** Represents the initializer for the table public.ContentTranslation */
export interface ContentTranslationInitializer {
  key: ContentTranslationKey;

  locale: Locale;

  value: string;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;

  updater_id?: UserId | null;
}

/** Represents the mutator for the table public.ContentTranslation */
export interface ContentTranslationMutator {
  key?: ContentTranslationKey;

  locale?: Locale;

  value?: string;

  updated_at?: Date;

  updater_id?: UserId | null;
}
