// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { Locale } from '../../../__generated__/resolvers-types';
import type { UserId } from './User';

/** Identifier type for public.ContentTranslationDraft */
export type ContentTranslationDraftKey = string & { __brand: 'public.ContentTranslationDraft' };

/** Identifier type for public.ContentTranslationDraft */
export type ContentTranslationDraftLocale = string & { __brand: 'public.ContentTranslationDraft' };

/** Represents the table public.ContentTranslationDraft */
export default interface ContentTranslationDraft {
  key: ContentTranslationDraftKey;

  locale: Locale;

  value: string;

  updated_at: Date;

  updater_id: UserId | null;
}

/** Represents the initializer for the table public.ContentTranslationDraft */
export interface ContentTranslationDraftInitializer {
  key: ContentTranslationDraftKey;

  locale: Locale;

  value: string;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;

  updater_id?: UserId | null;
}

/** Represents the mutator for the table public.ContentTranslationDraft */
export interface ContentTranslationDraftMutator {
  key?: ContentTranslationDraftKey;

  locale?: Locale;

  value?: string;

  updated_at?: Date;

  updater_id?: UserId | null;
}
