// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { DeploymentRequestPlatformRegion } from '../../../__generated__/resolvers-types';

/** Represents the table public.DeploymentRequestQuota */
export default interface DeploymentRequestQuota {
  id: string;

  region: DeploymentRequestPlatformRegion;

  capacity: number;

  availability: number;
}

/** Represents the initializer for the table public.DeploymentRequestQuota */
export interface DeploymentRequestQuotaInitializer {
  id: string;

  region: DeploymentRequestPlatformRegion;

  capacity: number;

  availability: number;
}

/** Represents the mutator for the table public.DeploymentRequestQuota */
export interface DeploymentRequestQuotaMutator {
  id?: string;

  region?: DeploymentRequestPlatformRegion;

  capacity?: number;

  availability?: number;
}
