// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './User';
import type { FiligranProduct, Timeline, EpicType, EditionType } from '../../../__generated__/resolvers-types';
import type { DocumentId } from './Document';

/** Identifier type for public.Epic */
export type EpicId = string & { __brand: 'public.Epic' };

/** Represents the table public.Epic */
export default interface Epic {
  id: EpicId;

  title: string;

  active: boolean;

  uploader_id: UserId;

  short_description: string;

  description: string;

  product: FiligranProduct[];

  timeline: Timeline;

  epic_type: EpicType;

  document_id: DocumentId | null;

  created_at: Date;

  updated_at: Date | null;

  updater_id: UserId | null;

  edition_type: EditionType;

  slack_link: string | null;
}

/** Represents the initializer for the table public.Epic */
export interface EpicInitializer {
  /** Default value: gen_random_uuid() */
  id?: EpicId;

  title: string;

  /** Default value: false */
  active?: boolean;

  uploader_id: UserId;

  short_description: string;

  description: string;

  product: FiligranProduct[];

  timeline?: Timeline;

  epic_type?: EpicType;

  document_id?: DocumentId | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  updated_at?: Date | null;

  updater_id?: UserId | null;

  edition_type?: EditionType;

  slack_link?: string | null;
}

/** Represents the mutator for the table public.Epic */
export interface EpicMutator {
  id?: EpicId;

  title?: string;

  active?: boolean;

  uploader_id?: UserId;

  short_description?: string;

  description?: string;

  product?: FiligranProduct[];

  timeline?: Timeline;

  epic_type?: EpicType;

  document_id?: DocumentId | null;

  created_at?: Date;

  updated_at?: Date | null;

  updater_id?: UserId | null;

  edition_type?: EditionType;

  slack_link?: string | null;
}
