// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.PulseSalt */
export type PulseSaltDay = Date & { __brand: 'public.PulseSalt' };

/** Represents the table public.PulseSalt */
export default interface PulseSalt {
  day: PulseSaltDay;

  salt: unknown;

  created_at: Date;
}

/** Represents the initializer for the table public.PulseSalt */
export interface PulseSaltInitializer {
  day: PulseSaltDay;

  salt: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.PulseSalt */
export interface PulseSaltMutator {
  day?: PulseSaltDay;

  salt?: unknown;

  created_at?: Date;
}
