// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.PulseBatch */
export type PulseBatchPseudonym = unknown & { __brand: 'public.PulseBatch' };

/** Identifier type for public.PulseBatch */
export type PulseBatchBatchId = string & { __brand: 'public.PulseBatch' };

/** Represents the table public.PulseBatch */
export default interface PulseBatch {
  pseudonym: PulseBatchPseudonym;

  batch_id: PulseBatchBatchId;

  day: Date;

  accepted: number;
}

/** Represents the initializer for the table public.PulseBatch */
export interface PulseBatchInitializer {
  pseudonym: PulseBatchPseudonym;

  batch_id: PulseBatchBatchId;

  day: Date;

  accepted: number;
}

/** Represents the mutator for the table public.PulseBatch */
export interface PulseBatchMutator {
  pseudonym?: PulseBatchPseudonym;

  batch_id?: PulseBatchBatchId;

  day?: Date;

  accepted?: number;
}
