// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PulsePeriod } from '../../../__generated__/resolvers-types';

/** Identifier type for public.PulseTrendingSnapshot */
export type PulseTrendingSnapshotDay = Date & { __brand: 'public.PulseTrendingSnapshot' };

/** Identifier type for public.PulseTrendingSnapshot */
export type PulseTrendingSnapshotPeriod = string & { __brand: 'public.PulseTrendingSnapshot' };

/** Identifier type for public.PulseTrendingSnapshot */
export type PulseTrendingSnapshotSectorScope = string & { __brand: 'public.PulseTrendingSnapshot' };

/** Identifier type for public.PulseTrendingSnapshot */
export type PulseTrendingSnapshotRegionScope = string & { __brand: 'public.PulseTrendingSnapshot' };

/** Represents the table public.PulseTrendingSnapshot */
export default interface PulseTrendingSnapshot {
  day: PulseTrendingSnapshotDay;

  period: PulsePeriod;

  sector_scope: PulseTrendingSnapshotSectorScope;

  region_scope: PulseTrendingSnapshotRegionScope;

  computed_at: Date;

  items: unknown;
}

/** Represents the initializer for the table public.PulseTrendingSnapshot */
export interface PulseTrendingSnapshotInitializer {
  day: PulseTrendingSnapshotDay;

  period: PulsePeriod;

  sector_scope: PulseTrendingSnapshotSectorScope;

  region_scope: PulseTrendingSnapshotRegionScope;

  /** Default value: CURRENT_TIMESTAMP */
  computed_at?: Date;

  items: unknown;
}

/** Represents the mutator for the table public.PulseTrendingSnapshot */
export interface PulseTrendingSnapshotMutator {
  day?: PulseTrendingSnapshotDay;

  period?: PulsePeriod;

  sector_scope?: PulseTrendingSnapshotSectorScope;

  region_scope?: PulseTrendingSnapshotRegionScope;

  computed_at?: Date;

  items?: unknown;
}
