// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.PulseDataGeneration */
export type PulseDataGenerationId = number & { __brand: 'public.PulseDataGeneration' };

/** Represents the table public.PulseDataGeneration */
export default interface PulseDataGeneration {
  id: PulseDataGenerationId;

  generation: number;
}

/** Represents the initializer for the table public.PulseDataGeneration */
export interface PulseDataGenerationInitializer {
  id: PulseDataGenerationId;

  /** Default value: 0 */
  generation?: number;
}

/** Represents the mutator for the table public.PulseDataGeneration */
export interface PulseDataGenerationMutator {
  id?: PulseDataGenerationId;

  generation?: number;
}
