// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PulsePlatformId } from './PulsePlatform';
import type { PulseObjectType, PulseEventKind, PulseSectorBucket, PulseRegionBucket } from '../../../__generated__/resolvers-types';

/** Identifier type for public.PulsePlatformDailyTotal */
export type PulsePlatformDailyTotalDay = Date & { __brand: 'public.PulsePlatformDailyTotal' };

/** Identifier type for public.PulsePlatformDailyTotal */
export type PulsePlatformDailyTotalObjectType = string & { __brand: 'public.PulsePlatformDailyTotal' };

/** Identifier type for public.PulsePlatformDailyTotal */
export type PulsePlatformDailyTotalEventKind = string & { __brand: 'public.PulsePlatformDailyTotal' };

/** Identifier type for public.PulsePlatformDailyTotal */
export type PulsePlatformDailyTotalSectorBucket = string & { __brand: 'public.PulsePlatformDailyTotal' };

/** Identifier type for public.PulsePlatformDailyTotal */
export type PulsePlatformDailyTotalRegionBucket = string & { __brand: 'public.PulsePlatformDailyTotal' };

/** Represents the table public.PulsePlatformDailyTotal */
export default interface PulsePlatformDailyTotal {
  pulse_platform_id: PulsePlatformId;

  day: PulsePlatformDailyTotalDay;

  object_type: PulseObjectType;

  event_kind: PulseEventKind;

  sector_bucket: PulseSectorBucket;

  region_bucket: PulseRegionBucket;

  event_count: string;
}

/** Represents the initializer for the table public.PulsePlatformDailyTotal */
export interface PulsePlatformDailyTotalInitializer {
  pulse_platform_id: PulsePlatformId;

  day: PulsePlatformDailyTotalDay;

  object_type: PulseObjectType;

  event_kind: PulseEventKind;

  sector_bucket: PulseSectorBucket;

  region_bucket: PulseRegionBucket;

  event_count: string;
}

/** Represents the mutator for the table public.PulsePlatformDailyTotal */
export interface PulsePlatformDailyTotalMutator {
  pulse_platform_id?: PulsePlatformId;

  day?: PulsePlatformDailyTotalDay;

  object_type?: PulseObjectType;

  event_kind?: PulseEventKind;

  sector_bucket?: PulseSectorBucket;

  region_bucket?: PulseRegionBucket;

  event_count?: string;
}
