// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PulseSectorBucket, PulseRegionBucket } from '../../../__generated__/resolvers-types';

/** Identifier type for public.PulsePlatform */
export type PulsePlatformId = number & { __brand: 'public.PulsePlatform' };

/** Represents the table public.PulsePlatform */
export default interface PulsePlatform {
  id: PulsePlatformId;

  pseudonym: unknown;

  sector_bucket: PulseSectorBucket;

  region_bucket: PulseRegionBucket;

  first_contribution_day: Date;

  last_contribution_day: Date;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.PulsePlatform */
export interface PulsePlatformInitializer {
  /** Default value: nextval('"PulsePlatform_id_seq"'::regclass) */
  id?: PulsePlatformId;

  pseudonym: unknown;

  sector_bucket: PulseSectorBucket;

  region_bucket: PulseRegionBucket;

  first_contribution_day: Date;

  last_contribution_day: Date;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.PulsePlatform */
export interface PulsePlatformMutator {
  id?: PulsePlatformId;

  pseudonym?: unknown;

  sector_bucket?: PulseSectorBucket;

  region_bucket?: PulseRegionBucket;

  first_contribution_day?: Date;

  last_contribution_day?: Date;

  created_at?: Date;

  updated_at?: Date;
}
