// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PulsePlatformId } from './PulsePlatform';
import type { PulseObjectType, PulseEventKind, PulseSectorBucket, PulseRegionBucket } from '../../../__generated__/resolvers-types';

/** Identifier type for public.PulseContribution */
export type PulseContributionDay = Date & { __brand: 'public.PulseContribution' };

/** Identifier type for public.PulseContribution */
export type PulseContributionAtRestKey = unknown & { __brand: 'public.PulseContribution' };

/** Identifier type for public.PulseContribution */
export type PulseContributionObjectType = string & { __brand: 'public.PulseContribution' };

/** Identifier type for public.PulseContribution */
export type PulseContributionEventKind = string & { __brand: 'public.PulseContribution' };

/** Identifier type for public.PulseContribution */
export type PulseContributionSectorBucket = string & { __brand: 'public.PulseContribution' };

/** Identifier type for public.PulseContribution */
export type PulseContributionRegionBucket = string & { __brand: 'public.PulseContribution' };

/** Represents the table public.PulseContribution */
export default interface PulseContribution {
  pulse_platform_id: PulsePlatformId;

  day: PulseContributionDay;

  at_rest_key: PulseContributionAtRestKey;

  object_type: PulseObjectType;

  event_kind: PulseEventKind;

  sector_bucket: PulseSectorBucket;

  region_bucket: PulseRegionBucket;

  event_count: string;

  updated_at: Date;
}

/** Represents the initializer for the table public.PulseContribution */
export interface PulseContributionInitializer {
  pulse_platform_id: PulsePlatformId;

  day: PulseContributionDay;

  at_rest_key: PulseContributionAtRestKey;

  object_type: PulseObjectType;

  event_kind: PulseEventKind;

  sector_bucket: PulseSectorBucket;

  region_bucket: PulseRegionBucket;

  event_count: string;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.PulseContribution */
export interface PulseContributionMutator {
  pulse_platform_id?: PulsePlatformId;

  day?: PulseContributionDay;

  at_rest_key?: PulseContributionAtRestKey;

  object_type?: PulseObjectType;

  event_kind?: PulseEventKind;

  sector_bucket?: PulseSectorBucket;

  region_bucket?: PulseRegionBucket;

  event_count?: string;

  updated_at?: Date;
}
