// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PulseObjectType } from '../../../__generated__/resolvers-types';

/** Identifier type for public.PulseKey */
export type PulseKeyAtRestKey = unknown & { __brand: 'public.PulseKey' };

/** Identifier type for public.PulseKey */
export type PulseKeyObjectType = string & { __brand: 'public.PulseKey' };

/** Represents the table public.PulseKey */
export default interface PulseKey {
  at_rest_key: PulseKeyAtRestKey;

  object_type: PulseObjectType;

  platform_count: number;
}

/** Represents the initializer for the table public.PulseKey */
export interface PulseKeyInitializer {
  at_rest_key: PulseKeyAtRestKey;

  object_type: PulseObjectType;

  platform_count: number;
}

/** Represents the mutator for the table public.PulseKey */
export interface PulseKeyMutator {
  at_rest_key?: PulseKeyAtRestKey;

  object_type?: PulseObjectType;

  platform_count?: number;
}
