// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.PulseRateLimit */
export type PulseRateLimitPseudonym = unknown & { __brand: 'public.PulseRateLimit' };

/** Identifier type for public.PulseRateLimit */
export type PulseRateLimitOperation = string & { __brand: 'public.PulseRateLimit' };

/** Identifier type for public.PulseRateLimit */
export type PulseRateLimitBucketStart = Date & { __brand: 'public.PulseRateLimit' };

/** Represents the table public.PulseRateLimit */
export default interface PulseRateLimit {
  pseudonym: PulseRateLimitPseudonym;

  operation: PulseRateLimitOperation;

  bucket_start: PulseRateLimitBucketStart;

  request_count: number;
}

/** Represents the initializer for the table public.PulseRateLimit */
export interface PulseRateLimitInitializer {
  pseudonym: PulseRateLimitPseudonym;

  operation: PulseRateLimitOperation;

  bucket_start: PulseRateLimitBucketStart;

  request_count: number;
}

/** Represents the mutator for the table public.PulseRateLimit */
export interface PulseRateLimitMutator {
  pseudonym?: PulseRateLimitPseudonym;

  operation?: PulseRateLimitOperation;

  bucket_start?: PulseRateLimitBucketStart;

  request_count?: number;
}
