// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PulseObjectType } from '../../../__generated__/resolvers-types';
import type { PulsePlatformId } from './PulsePlatform';

/** Identifier type for public.PulseKeyContributor */
export type PulseKeyContributorAtRestKey = unknown & { __brand: 'public.PulseKeyContributor' };

/** Identifier type for public.PulseKeyContributor */
export type PulseKeyContributorObjectType = string & { __brand: 'public.PulseKeyContributor' };

/** Represents the table public.PulseKeyContributor */
export default interface PulseKeyContributor {
  at_rest_key: PulseKeyContributorAtRestKey;

  object_type: PulseObjectType;

  pulse_platform_id: PulsePlatformId;

  last_day: Date;
}

/** Represents the initializer for the table public.PulseKeyContributor */
export interface PulseKeyContributorInitializer {
  at_rest_key: PulseKeyContributorAtRestKey;

  object_type: PulseObjectType;

  pulse_platform_id: PulsePlatformId;

  last_day: Date;
}

/** Represents the mutator for the table public.PulseKeyContributor */
export interface PulseKeyContributorMutator {
  at_rest_key?: PulseKeyContributorAtRestKey;

  object_type?: PulseObjectType;

  pulse_platform_id?: PulsePlatformId;

  last_day?: Date;
}
