// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.PulseDigestSnapshot */
export type PulseDigestSnapshotDay = Date & { __brand: 'public.PulseDigestSnapshot' };

/** Represents the table public.PulseDigestSnapshot */
export default interface PulseDigestSnapshot {
  day: PulseDigestSnapshotDay;

  computed_at: Date;

  items: unknown;
}

/** Represents the initializer for the table public.PulseDigestSnapshot */
export interface PulseDigestSnapshotInitializer {
  day: PulseDigestSnapshotDay;

  /** Default value: CURRENT_TIMESTAMP */
  computed_at?: Date;

  items: unknown;
}

/** Represents the mutator for the table public.PulseDigestSnapshot */
export interface PulseDigestSnapshotMutator {
  day?: PulseDigestSnapshotDay;

  computed_at?: Date;

  items?: unknown;
}
