// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PulseObjectType, PulseSectorBucket, PulseRegionBucket } from '../../../__generated__/resolvers-types';

/** Identifier type for public.PulseDailyAggregate */
export type PulseDailyAggregateAtRestKey = unknown & { __brand: 'public.PulseDailyAggregate' };

/** Identifier type for public.PulseDailyAggregate */
export type PulseDailyAggregateObjectType = string & { __brand: 'public.PulseDailyAggregate' };

/** Identifier type for public.PulseDailyAggregate */
export type PulseDailyAggregateDay = Date & { __brand: 'public.PulseDailyAggregate' };

/** Identifier type for public.PulseDailyAggregate */
export type PulseDailyAggregateSectorBucket = string & { __brand: 'public.PulseDailyAggregate' };

/** Identifier type for public.PulseDailyAggregate */
export type PulseDailyAggregateRegionBucket = string & { __brand: 'public.PulseDailyAggregate' };

/** Represents the table public.PulseDailyAggregate */
export default interface PulseDailyAggregate {
  at_rest_key: PulseDailyAggregateAtRestKey;

  object_type: PulseObjectType;

  day: PulseDailyAggregateDay;

  sector_bucket: PulseSectorBucket;

  region_bucket: PulseRegionBucket;

  platform_count: number;

  created_count: string;

  sighted_count: string;

  detected_count: string;

  hunted_count: string;

  referenced_count: string;

  updated_at: Date;
}

/** Represents the initializer for the table public.PulseDailyAggregate */
export interface PulseDailyAggregateInitializer {
  at_rest_key: PulseDailyAggregateAtRestKey;

  object_type: PulseObjectType;

  day: PulseDailyAggregateDay;

  sector_bucket: PulseSectorBucket;

  region_bucket: PulseRegionBucket;

  platform_count: number;

  /** Default value: '0'::bigint */
  created_count?: string;

  /** Default value: '0'::bigint */
  sighted_count?: string;

  /** Default value: '0'::bigint */
  detected_count?: string;

  /** Default value: '0'::bigint */
  hunted_count?: string;

  /** Default value: '0'::bigint */
  referenced_count?: string;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.PulseDailyAggregate */
export interface PulseDailyAggregateMutator {
  at_rest_key?: PulseDailyAggregateAtRestKey;

  object_type?: PulseObjectType;

  day?: PulseDailyAggregateDay;

  sector_bucket?: PulseSectorBucket;

  region_bucket?: PulseRegionBucket;

  platform_count?: number;

  created_count?: string;

  sighted_count?: string;

  detected_count?: string;

  hunted_count?: string;

  referenced_count?: string;

  updated_at?: Date;
}
