// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { OrganizationId } from './Organization';
import type { UserAccountStatus } from '../../../__generated__/resolvers-types';

/** Identifier type for public.User */
export type UserId = string & { __brand: 'public.User' };

/** Represents the table public.User */
export default interface User {
  id: UserId;

  email: string;

  salt: string;

  password: string;

  first_name: string | null;

  last_name: string | null;

  selected_organization_id: OrganizationId;

  picture: string | null;

  disabled: boolean | null;

  last_login: Date | null;

  country: string | null;

  platform_token: string | null;

  picture_minio: string | null;

  selected_language: string;

  status: UserAccountStatus | null;

  invitation_date: Date | null;
}

/** Represents the initializer for the table public.User */
export interface UserInitializer {
  id: UserId;

  email: string;

  salt: string;

  password: string;

  first_name?: string | null;

  last_name?: string | null;

  selected_organization_id: OrganizationId;

  picture?: string | null;

  disabled?: boolean | null;

  last_login?: Date | null;

  country?: string | null;

  platform_token?: string | null;

  picture_minio?: string | null;

  /** Default value: 'en'::character varying */
  selected_language?: string;

  status?: UserAccountStatus | null;

  invitation_date?: Date | null;
}

/** Represents the mutator for the table public.User */
export interface UserMutator {
  id?: UserId;

  email?: string;

  salt?: string;

  password?: string;

  first_name?: string | null;

  last_name?: string | null;

  selected_organization_id?: OrganizationId;

  picture?: string | null;

  disabled?: boolean | null;

  last_login?: Date | null;

  country?: string | null;

  platform_token?: string | null;

  picture_minio?: string | null;

  selected_language?: string;

  status?: UserAccountStatus | null;

  invitation_date?: Date | null;
}
