enum IntegrationType {
  csv_feed
  connector
  rss_feed
  taxii_feed
  stream
  third_party_integration
}

interface Integration implements Node & Document {
  # Node
  id: ID!

  # Document
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  solution_categories: [SolutionCategory!]
  service_instance_id: ServiceInstanceId
  service_instance: ServiceInstance @auth
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResource!]

  # Integration
  remover_id: ID
  integration_type: IntegrationType!
  datasheet_url: String
  blogpost_url: String
  demo_url: String
  license_type: LicenseType
}

# Strictly equal to Integration. Otherwise we have typing issues because no type overlaps
type IntegrationHack implements Node & Document & Integration {
  # Node
  id: ID!

  # Document
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  solution_categories: [SolutionCategory!]
  service_instance_id: ServiceInstanceId
  service_instance: ServiceInstance @auth
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResource!]

  # Integration
  remover_id: ID
  integration_type: IntegrationType!
  datasheet_url: String
  blogpost_url: String
  demo_url: String
  license_type: LicenseType
}

type CsvFeed implements Node & Document & Integration {
  # Node
  id: ID!

  # Document
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  solution_categories: [SolutionCategory!]
  service_instance_id: ServiceInstanceId
  service_instance: ServiceInstance @auth
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResource!]

  # Integration
  remover_id: ID
  feed_url: String
  integration_type: IntegrationType!
  datasheet_url: String
  blogpost_url: String
  demo_url: String
  license_type: LicenseType
}

type Connector implements Node & Document & Integration {
  # Node
  id: ID!

  # Document
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  solution_categories: [SolutionCategory!]
  service_instance_id: ServiceInstanceId
  service_instance: ServiceInstance @auth
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResource!]

  # Integration
  remover_id: ID @auth
  integration_type: IntegrationType!
  product_version: String
  version: String
  container_image: String
  verified: Boolean!
  source_code: String
  subscription_link: String
  manager_supported: Boolean!
  playbook_supported: Boolean!
  datasheet_url: String
  blogpost_url: String
  demo_url: String
  minimum_deployable_version: String
  license_type: LicenseType
  contact: String
}

type TaxiiFeed implements Node & Document & Integration {
  # Node
  id: ID!

  # Document
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  solution_categories: [SolutionCategory!]
  service_instance_id: ServiceInstanceId
  service_instance: ServiceInstance @auth
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResource!]

  # Integration
  remover_id: ID @auth
  feed_url: String
  integration_type: IntegrationType!
  datasheet_url: String
  blogpost_url: String
  demo_url: String
  license_type: LicenseType
}
type RssFeed implements Node & Document & Integration {
  # Node
  id: ID!

  # Document
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  solution_categories: [SolutionCategory!]
  service_instance_id: ServiceInstanceId
  service_instance: ServiceInstance @auth
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResource!]

  # Integration
  remover_id: ID @auth
  feed_url: String
  integration_type: IntegrationType!
  datasheet_url: String
  blogpost_url: String
  demo_url: String
  license_type: LicenseType
}

type Stream implements Node & Document & Integration {
  # Node
  id: ID!

  # Document
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  solution_categories: [SolutionCategory!]
  service_instance_id: ServiceInstanceId
  service_instance: ServiceInstance @auth
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResource!]

  # Integration
  remover_id: ID @auth
  feed_url: String
  integration_type: IntegrationType!
  datasheet_url: String
  blogpost_url: String
  demo_url: String
  license_type: LicenseType
}

type ThirdPartyIntegration implements Node & Document & Integration {
  # Node
  id: ID!

  # Document
  type: String!
  uploader: User
  uploader_organization: Organization
  name: String!
  short_description: String
  description: String
  file_name: String @auth
  active: Boolean!
  created_at: Date!
  updated_at: Date
  updater_id: String @auth
  download_number: Int
  share_number: Int
  slug: String!
  use_cases: [UseCase!]
  solution_categories: [SolutionCategory!]
  service_instance_id: ServiceInstanceId
  service_instance: ServiceInstance @auth
  subscription: SubscriptionModel @auth
  children_documents: [ShareableResource!]

  # Integration
  remover_id: ID @auth
  integration_type: IntegrationType!
  vendor_url: String!
  product_version: String
  github_url: String
  datasheet_url: String
  blogpost_url: String
  demo_url: String
  license_type: LicenseType
}
