scalar ServiceInstanceId

enum ServiceInstanceOrdering {
  name
  description
  ordering
}

enum ServiceInstanceCreationStatus {
  DISABLED
  PENDING
  CREATED
  READY
}

enum ServiceInstanceTag {
  openCTI
  openAEV
  xtmOne
  trial
  others
}

enum ServiceInstanceFilterKey {
  id
  tags
  service_definition_identifier
  public
}

input ServiceInstanceFilter {
  key: ServiceInstanceFilterKey
  value: [String!]!
}

type ServiceInstance implements Node {
  id: ID!
  name: String!
  description: String
  slug: String
  creation_status: ServiceInstanceCreationStatus
  organization_subscribed: Boolean
  user_joined: Boolean
  links: [ServiceLink]
  organization: [Organization]
  subscriptions: [SubscriptionModel]
  capabilities: [String]!
  public: Boolean
  tags: [ServiceInstanceTag!]
  service_definition: ServiceDefinition
  logo_document_id: DocumentId
  illustration_document_id: DocumentId
  ordering: Int!
}

type ServiceInstanceEdge {
  cursor: String!
  node: ServiceInstance
}

type ServiceConnection {
  totalCount: Int!
  edges: [ServiceInstanceEdge!]!
  pageInfo: PageInfo!
}
type SeoServiceInstance implements Node {
  id: ID!
  name: String!
  slug: String
  description: String
  links: [ServiceLink]
  tags: [ServiceInstanceTag!]
  service_definition: ServiceDefinition!
  logo_document_id: DocumentId
  illustration_document_id: DocumentId
}

input AddServiceInput {
  service_instance_name: String
  service_instance_description: String
  fee_type: String
  price: Int
  organization_id: String
  url: String
}

input UpdatePlatformServiceMetadataInput {
  serviceInstanceId: ServiceInstanceId!
  name: String
}

type Mutation {
  addServicePicture(
    serviceInstanceId: ServiceInstanceId!
    document: Upload
    isLogo: Boolean!
  ): ServiceInstance
    @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_SUBSCRIPTION])
  updatePlatformServiceMetadata(
    input: UpdatePlatformServiceMetadataInput!
  ): RegisteredPlatform
    @auth(orgaCapa: [ADMINISTRATE_ORGANIZATION, MANAGE_PLATFORM_REGISTRATION])
}

type Query {
  serviceInstances(
    first: Int!
    after: ID
    orderBy: ServiceInstanceOrdering!
    orderMode: OrderingMode!
    searchTerm: String
    filters: [ServiceInstanceFilter!]
    includeInaccessible: Boolean
  ): ServiceConnection! @auth
  serviceInstanceLinksByTags(
    tags: [ServiceInstanceTag!]!
  ): [SeoServiceInstance!]!
  serviceInstanceById(service_instance_id: ServiceInstanceId!): ServiceInstance
    @auth
  seoServiceInstances: [SeoServiceInstance!]!
  seoServiceInstance(slug: String!): SeoServiceInstance!
}

type SubscribedServiceInstanceConfiguration {
  token: String!
  platform_id: String!
  platform_url: String!
  registerer_id: String!
  platform_title: String!
  platform_contract: PlatformContract!
}

type ServiceInstanceSubscription {
  add: ServiceInstance
  edit: ServiceInstance
  delete: ServiceInstance
}

type Subscription {
  ServiceInstance: ServiceInstanceSubscription @auth
}
