export enum ForbiddenErrorCode {
  MissingCapabilityOnOrganization = 'MISSING_CAPABILITY_ON_ORGANIZATION',
  MissingCapabilityOnService = 'MISSING_CAPABILITY_ON_SERVICE',
  ServiceInstanceNotPublic = 'SERVICE_INSTANCE_NOT_PUBLIC',
  RegistrationOnAnotherOrganizationForbidden = 'REGISTRATION_ON_ANOTHER_ORGANIZATION_FORBIDDEN',
  UserIsNotInOrganization = 'USER_IS_NOT_IN_ORGANIZATION',
  AlreadySubscribed = 'ALREADY_SUBSCRIBED',
  EditCapabilitiesCantRemoveLastManageAccess = 'EDIT_CAPABILITIES_CANT_REMOVE_LAST_MANAGE_ACCESS',
  GrantCapabilitiesOnOrganizationFirst = 'GRANT_CAPABILITIES_ON_ORGANIZATION_FIRST',
  CantSubscribeYourself = 'CANT_SUBSCRIBE_YOURSELF',
  UserDisabled = 'USER_DISABLED',
  CantRemoveLastAdministrator = 'CANT_REMOVE_LAST_ADMINISTRATOR',
  CantAddUserToPersonalSpace = 'CANT_ADD_USER_TO_PERSONAL_SPACE',
  EmailOutsideOrganizationError = 'EMAIL_OUTSIDE_ORGANIZATION_ERROR',
  CantAddDisabledUser = 'CANT_ADD_DISABLED_USER',
  CantRemoveYourselfFromOrgaError = 'CANT_REMOVE_YOURSELF_FROM_ORGA_ERROR',
  YouCanNotLogin = 'YOU_CAN_NOT_LOGIN',
  PlatformTypeNotSupported = 'PLATFORM_TYPE_NOT_SUPPORTED',
  CantRequestFreeTrialInPersonalSpace = 'CANT_REQUEST_FREE_TRIAL_IN_PERSONAL_SPACE',
  CantRequestFreeTrial = 'CANT_REQUEST_FREE_TRIAL',
  CantCancelBundleProduct = 'CANT_CANCEL_BUNDLE_PRODUCT',
  NotAllowedByDeploymentStatus = 'NOT_ALLOWED_BY_DEPLOYMENT_STATUS',
  IntegrationTypeNotManageable = 'INTEGRATION_TYPE_NOT_MANAGEABLE',
  ServiceNotManageable = 'SERVICE_NOT_MANAGEABLE',
  CantDeleteYourself = 'CANT_DELETE_YOURSELF',
  CantDeleteBuiltinUser = 'CANT_DELETE_BUILTIN_USER',
  DeleteUserBlockedByTransferRequest = 'DELETE_USER_BLOCKED_BY_TRANSFER_REQUEST',
  DeleteUserBlockedByDeploymentRequest = 'DELETE_USER_BLOCKED_BY_DEPLOYMENT_REQUEST',
  DeleteUserBlockedByCancellationRecord = 'DELETE_USER_BLOCKED_BY_CANCELLATION_RECORD',
  DeleteUserBlockedByPendingUsers = 'DELETE_USER_BLOCKED_BY_PENDING_USERS',
  DeleteUserBlockedByPlatformRegistration = 'DELETE_USER_BLOCKED_BY_PLATFORM_REGISTRATION',
  DeleteUserBlockedByLastOrganizationMember = 'DELETE_USER_BLOCKED_BY_LAST_ORGANIZATION_MEMBER',
  DeleteUserBlockedByLinkedData = 'DELETE_USER_BLOCKED_BY_LINKED_DATA',
  DeleteOrganizationPendingUsers = 'DELETE_ORGANIZATION_PENDING_USERS',
  DeleteOrganizationRequiresSingleUser = 'DELETE_ORGANIZATION_REQUIRES_SINGLE_USER',
  DeleteOrganizationBlockedByConnectedProduct = 'DELETE_ORGANIZATION_BLOCKED_BY_CONNECTED_PRODUCT',
  VotingRoundNotOpen = 'VOTING_ROUND_NOT_OPEN',
  VotingRoundClosed = 'VOTING_ROUND_CLOSED',
  DeleteVotingRoundBlockedByVotes = 'DELETE_VOTING_ROUND_BLOCKED_BY_VOTES',
  DeleteVotableFeatureBlockedByVotes = 'DELETE_VOTABLE_FEATURE_BLOCKED_BY_VOTES',
  VotableFeatureProductLocked = 'VOTABLE_FEATURE_PRODUCT_LOCKED',
  CopyFeaturesFromAnotherRoadmap = 'COPY_FEATURES_FROM_ANOTHER_ROADMAP',
  OpenVotingRoundWithoutActiveFeature = 'OPEN_VOTING_ROUND_WITHOUT_ACTIVE_FEATURE',
}

export enum BadRequestErrorCode {
  InvalidImageUrl = 'INVALID_IMAGE_URL',
  InvalidPlatformConfiguration = 'INVALID_PLATFORM_CONFIGURATION',
  PlatformNotRegistered = 'PLATFORM_NOT_REGISTERED',
  InvalidPlatformIdentifier = 'INVALID_PLATFORM_IDENTIFIER',
  InvalidActionSize = 'INVALID_ACTION_SIZE',
  InvalidEmail = 'INVALID_EMAIL',
  MissingStartOrEndDate = 'MISSING_START_OR_END_DATE',
  DeploymentRequestStatusUpdateNotAllowed = 'DEPLOYMENT_REQUEST_STATUS_UPDATE_NOT_ALLOWED',
  InvalidPlatformId = 'INVALID_PLATFORM_ID',
  InvalidPlatformVersion = 'INVALID_PLATFORM_VERSION',
  ServiceGroupsLinkedToMultipleServiceInstances = 'SERVICE_GROUPS_LINKED_TO_MULTIPLE_SERVICE_INSTANCES',
  OrganizationDoesNotMatchSelectedOrganization = 'ORGANIZATIONS_DOES_NOT_MATCH_SELECTED_ORGANIZATION',
  DeploymentRequestHubStatusNotQueued = 'DEPLOYMENT_REQUEST_HUB_STATUS_NOT_QUEUED',
  DocumentMissingMetadata = 'DOCUMENT_MISSING_METADATA',
  IntegrationTypeNotRecognized = 'INTEGRATION_TYPE_NOT_RECOGNIZED',
  MissingAutoRegisterPlatformArgument = 'MISSING_AUTO_REGISTER_PLATFORM_ARGUMENT',
  DocumentFileMissing = 'DOCUMENT_FILE_MISSING',
  TenantIdMandatory = 'TENANT_ID_MANDATORY',
  NewsFeedItemMissingTitle = 'NEWS_FEED_ITEM_MISSING_TITLE',
  InvalidManifestVersionFormat = 'INVALID_MANIFEST_VERSION_FORMAT',
  ConnectorVersionAlreadyExists = 'CONNECTOR_VERSION_ALREADY_EXISTS',
  ConnectorIdAlreadyExists = 'CONNECTOR_ID_ALREADY_EXISTS',
  ShortDescriptionTooLong = 'SHORT_DESCRIPTION_TOO_LONG',
  ContactTooLong = 'CONTACT_TOO_LONG',
  MixedLtsManifestFragments = 'MIXED_LTS_MANIFEST_FRAGMENTS',
  InvalidProductsForDeploymentType = 'INVALID_PRODUCTS_FOR_DEPLOYMENT_TYPE',
  InvalidUseCasesForProducts = 'INVALID_USE_CASES_FOR_PRODUCTS',
  SolutionCategoriesRequired = 'SOLUTION_CATEGORIES_REQUIRED',
  XtmOneRoleRequired = 'XTM_ONE_ROLE_REQUIRED',
}

export enum UnknownErrorCode {
  CanUnregisterPlatformUnknownError = 'CAN_UNREGISTER_PLATFORM_UNKNOWN_ERROR',
  IsPlatformRegisteredUnknownError = 'IS_PLATFORM_REGISTERED_UNKNOWN_ERROR',
  RefreshUserPlatformTokenUnknownError = 'REFRESH_USER_PLATFORM_TOKEN_UNKNOWN_ERROR',
  RegisterPlatformUnknownError = 'REGISTER_PLATFORM_UNKNOWN_ERROR',
  UnknownError = 'UNKNOWN_ERROR',
  UnregisterPlatformUnknownError = 'UNREGISTER_PLATFORM_UNKNOWN_ERROR',
  AddOrganizationError = 'ADD_ORGANIZATION_ERROR',
  EditOrganizationError = 'EDIT_ORGANIZATION_ERROR',
  DeleteOrganizationError = 'DELETE_ORGANIZATION_ERROR',
  DocumentCreateError = 'DOCUMENT_CREATE_ERROR',
  EpicCreateError = 'EPIC_CREATE_ERROR',
  DocumentUpdateError = 'DOCUMENT_UPDATE_ERROR',
  EpicUpdateError = 'EPIC_UPDATE_ERROR',
  DeleteDocumentError = 'DELETE_DOCUMENT_ERROR',
  EpicDeleteError = 'DELETE_EPIC_ERROR',
  IncrementShareNumberError = 'INCREMENT_SHARE_NUMBER',
  ServiceSubscriptionError = 'SERVICE_SUBSCRIPTION_ERROR',
  DeleteSubscriptionError = 'DELETE_SUBSCRIPTION_ERROR',
  EditCapabilitiesError = 'EDIT_CAPABILITIES_ERROR',
  AddCapabilitiesError = 'ADD_CAPABILITIES_ERROR',
  LoadCapabilitiesError = 'LOAD_CAPABILITIES_ERROR',
  AddUserServiceError = 'ADD_USER_SERVICE_ERROR',
  AddingUserError = 'ADDING_USER_ERROR',
  EditUserError = 'EDIT_USER_ERROR',
  DeleteUserError = 'DELETE_USER_ERROR',
  EditMeUserError = 'EDIT_ME_USER_ERROR',
  UploadUserPictureError = 'UPLOAD_USER_PICTURE_ERROR',
  TransferMeError = 'TRANSFER_ME_ERROR',
  RemoveUserFromOrgaError = 'REMOVE_USER_FROM_ORGA_ERROR',
  RemoveUserFromPendingOrgaError = 'REMOVE_USER_FROM_PENDING_ORGA_ERROR',
  AcceptUserInPendingOrgaError = 'ACCEPT_USER_IN_PENDING_ORGA_ERROR',
  UpdatePlatformServiceMetadataError = 'UPDATE_PLATFORM_SERVICE_METADATA_ERROR',
  NoAsyncContextAvailableError = 'NO_ASYNC_CONTEXT_AVAILABLE',
  CreateDeploymentRequestError = 'CREATE_DEPLOYMENT_REQUEST_ERROR',
  DeploymentRequestUnknownError = 'DEPLOYMENT_REQUEST_UNKNOWN_ERROR',
  HubspotError = 'HUBSPOT_ERROR',
  MissingMetadataMapping = 'MISSING_METADATA_MAPPING',
  VoteForFeatureError = 'VOTE_FOR_FEATURE_ERROR',
  VotingRoundMutationError = 'VOTING_ROUND_MUTATION_ERROR',
  VotableFeatureMutationError = 'VOTABLE_FEATURE_MUTATION_ERROR',
  ListFacetError = 'LIST_FACET_ERROR',
}

export enum AlreadyExistsErrorCode {
  OrganizationSameNameExists = 'ORGANIZATION_SAME_NAME_EXISTS',
  OrganizationSameDomainExists = 'ORGANIZATION_SAME_DOMAIN_EXISTS',
  DocumentUniqueSlugError = 'DOCUMENT_UNIQUE_SLUG_ERROR',
  FreeTrialAlreadyExists = 'FREE_TRIAL_ALREADY_EXISTS',
  CompetitorDomainAlreadyExists = 'COMPETITOR_DOMAIN_ALREADY_EXISTS',
}

export enum NotFoundErrorCode {
  ServiceInstanceNotFound = 'SERVICE_INSTANCE_NOT_FOUND',
  SeoServiceInstanceNotFound = 'SEO_SERVICE_INSTANCE_NOT_FOUND',
  ServiceDefinitionNotFound = 'SERVICE_DEFINITION_NOT_FOUND',
  SubscriptionNotFound = 'SUBSCRIPTION_NOT_FOUND',
  ServiceNotFound = 'SERVICE_NOT_FOUND',
  PlatformConfigurationNotFound = 'PLATFORM_CONFIGURATION_NOT_FOUND',
  DeploymentRequestNotFound = 'DEPLOYMENT_REQUEST_NOT_FOUND',
  DeploymentRequestQuotaNotFound = 'DEPLOYMENT_REQUEST_QUOTA_NOT_FOUND',
  DocumentNotFound = 'DOCUMENT_NOT_FOUND',
  NewsFeedItemNotFound = 'NEWS_FEED_ITEM_NOT_FOUND',
  UserNotFound = 'USER_NOT_FOUND',
  CompetitorNotFound = 'COMPETITOR_NOT_FOUND',
  OrganizationNotFound = 'ORGANIZATION_NOT_FOUND',
  UseCaseNotFound = 'USE_CASE_NOT_FOUND',
  SolutionCategoryNotFound = 'SOLUTION_CATEGORY_NOT_FOUND',
  ServiceGroupNotFound = 'SERVICE_GROUP_NOT_FOUND',
  VotableFeatureNotFound = 'VOTABLE_FEATURE_NOT_FOUND',
  VotingRoundNotFound = 'VOTING_ROUND_NOT_FOUND',
}

export const ErrorCode = {
  ...ForbiddenErrorCode,
  ...BadRequestErrorCode,
  ...AlreadyExistsErrorCode,
  ...NotFoundErrorCode,
};
