type SeoServiceInstanceMetadata {
  service_instance_id: ServiceInstanceId!
  language: Locale!
  meta_title: String!
  meta_description: String!
}

input EditSeoServiceInstanceInput {
  meta_title: String!
  meta_description: String!
}

type Query {
  seoServiceInstanceMetadata(
    service_instance_id: ServiceInstanceId!
    language: Locale
  ): [SeoServiceInstanceMetadata!]!
}

type Mutation {
  editSeoServiceInstance(
    service_instance_id: ServiceInstanceId!
    language: Locale!
    input: EditSeoServiceInstanceInput!
  ): SeoServiceInstanceMetadata!
    @auth(portalCapa: [BYPASS, MODIFY_SERVICE_METADATA])
}
