fragment PublicDocumentByServiceSlugItem on Document {
  __typename
  id
  name
  description
  short_description
  created_at
  updated_at
  slug
  download_number
  share_number
  children_documents {
    id
    image_type
    source_type
  }
  use_cases {
    id
    name
    color
  }
  uploader {
    first_name
    last_name
    picture
  }
  active
  type
  uploader_organization {
    id
    personal_space
    name
  }

  ... on Integration {
    integration_type
    datasheet_url
    blogpost_url
    demo_url
    solution_categories {
      id
      name
    }
    license_type
  }

  ... on CustomDashboard {
    product_version
  }

  ... on CsvFeed {
    feed_url
  }

  ... on TaxiiFeed {
    feed_url
  }

  ... on RssFeed {
    feed_url
  }

  ... on Stream {
    feed_url
  }

  ... on ThirdPartyIntegration {
    product_version
    vendor_url
    github_url
  }

  ... on Connector {
    product_version
    container_image
    verified
    source_code
    subscription_link
    manager_supported
    playbook_supported
    minimum_deployable_version
    contact
  }

  ... on OpenAEVScenario {
    product_version
  }

  ... on CustomView {
    product_version
    entity_types
  }
}

query PublicDocumentsByServiceSlugQuery($serviceInstanceSlug: String!) {
  publicDocumentsByServiceSlug(serviceInstanceSlug: $serviceInstanceSlug) {
    ...PublicDocumentByServiceSlugItem
  }
}

query PublicDocumentsByServiceSlugSitemapQuery($serviceInstanceSlug: String!) {
  publicDocumentsByServiceSlug(serviceInstanceSlug: $serviceInstanceSlug) {
    slug
    created_at
    updated_at
  }
}
