import { documentItem_fragment$data } from '@generated/documentItem_fragment.graphql';
import type { publicDocumentBySlugItemFragment$data } from '@generated/publicDocumentBySlugItemFragment.graphql';
import type { publicDocumentListItemFragment$data } from '@generated/publicDocumentListItemFragment.graphql';
import {
  PublicDocumentByServiceSlugItemFragment,
  ServiceDefinitionIdentifier,
} from '@graphql/generated';

/**
 * Shape of one item of the `publicDocumentsByServiceSlug` query response,
 * fetched server-side via `serverGraphqlFetch` and generated by
 * graphql-codegen from `graphql/document/public-document.query.graphql`.
 * Discriminated union per `Document` subtype — narrow on `__typename`
 * before reading a type-specific field (e.g. `integration_type`).
 */
export type PublicDocumentByServiceSlugItem =
  PublicDocumentByServiceSlugItemFragment;

/** Shape of the sitemap-only `publicDocumentsByServiceSlug` response. */
export type PublicDocumentSitemapItem = {
  slug: string | null;
  created_at: string;
  updated_at: string | null;
};

export type PublicDocumentData =
  | publicDocumentListItemFragment$data
  | PublicDocumentByServiceSlugItem
  | publicDocumentBySlugItemFragment$data;

export type PublicDocumentDetailsData =
  PublicDocumentByServiceSlugItem | publicDocumentBySlugItemFragment$data;

/**
 * Fields only present on `Document`s implementing the `Integration`
 * GraphQL interface. Used to narrow a document union via `isIntegrationItem`.
 *
 * `integration_type`/`license_type` are widened to `string`/`string | null`
 * instead of the `IntegrationType`/`LicenseType` enums: Relay generates its
 * own local literal-union type per fragment for these fields, and
 * intersecting it with the schema enum collapses to `never`. Cast to the
 * enum at call sites that need it (e.g. `as IntegrationType`).
 */
export type IntegrationFields = {
  integration_type: string;
  datasheet_url: string | null;
  blogpost_url: string | null;
  demo_url: string | null;
  solution_categories: ReadonlyArray<{ id: string; name: string }> | null;
  license_type: string | null;
};

/** Fields only present on `Connector` documents (a subtype of `Integration`). */
export type ConnectorFields = IntegrationFields & {
  product_version: string | null;
  container_image: string | null;
  verified: boolean;
  source_code: string | null;
  subscription_link: string | null;
  manager_supported: boolean;
  playbook_supported: boolean;
  minimum_deployable_version: string | null;
  contact: string | null;
};

export enum ShareableResourceType {
  OPENAEV_SCENARIO = 'openaev_scenario',
  OPENCTI_INTEGRATION = 'opencti_integration',
  OPENCTI_CUSTOM_DASHBOARD = 'opencti_custom_dashboard',
  OPENCTI_CUSTOM_VIEW = 'opencti_custom_view',
  OPENCTI_PLAYBOOK = 'opencti_playbook',
}

export type ServiceInfo = { link: string; description: string };
export enum ServiceSlug {
  OPEN_CTI_INTEGRATIONS = 'opencti-integrations',
  OPEN_CTI_CUSTOM_DASHBOARDS = 'opencti-custom-dashboards',
  OPEN_CTI_CUSTOM_VIEWS = 'opencti-custom-views',
  OPEN_AEV_SCENARIOS = 'openaev-scenarios',
  OPEN_CTI_PLAYBOOKS = 'opencti-playbooks',
}

export const SHAREABLE_RESOURCE_TYPE_NAME_MAPPING: Record<
  ShareableResourceType,
  string
> = {
  [ShareableResourceType.OPENAEV_SCENARIO]: 'Scenario OpenAEV',
  [ShareableResourceType.OPENCTI_INTEGRATION]: 'Integration OpenCTI',
  [ShareableResourceType.OPENCTI_CUSTOM_DASHBOARD]: 'Custom Dashboard OpenCTI',
  [ShareableResourceType.OPENCTI_CUSTOM_VIEW]: 'Custom View OpenCTI',
  [ShareableResourceType.OPENCTI_PLAYBOOK]: 'Playbook OpenCTI',
};

export const SHAREABLE_RESOURCE_PRODUCT_MAPPING: Record<
  ShareableResourceType,
  string
> = {
  [ShareableResourceType.OPENAEV_SCENARIO]: 'OpenAEV',
  [ShareableResourceType.OPENCTI_INTEGRATION]: 'OpenCTI',
  [ShareableResourceType.OPENCTI_CUSTOM_DASHBOARD]: 'OpenCTI',
  [ShareableResourceType.OPENCTI_CUSTOM_VIEW]: 'OpenCTI',
  [ShareableResourceType.OPENCTI_PLAYBOOK]: 'OpenCTI',
};

export const SHAREABLE_RESOURCE_LIBRARY_MAPPING: Record<
  ShareableResourceType,
  string
> = {
  [ShareableResourceType.OPENAEV_SCENARIO]: 'Scenarios',
  [ShareableResourceType.OPENCTI_INTEGRATION]: 'Integrations',
  [ShareableResourceType.OPENCTI_CUSTOM_DASHBOARD]: 'Custom Dashboards',
  [ShareableResourceType.OPENCTI_CUSTOM_VIEW]: 'Custom Views',
  [ShareableResourceType.OPENCTI_PLAYBOOK]: 'Playbooks',
};

export const SHAREABLE_RESOURCE_SERVICE_DEFINITION_IDENTIFIER_MAPPING: Record<
  ShareableResourceType,
  ServiceDefinitionIdentifier
> = {
  [ShareableResourceType.OPENCTI_INTEGRATION]:
    ServiceDefinitionIdentifier.OpenctiIntegrations,
  [ShareableResourceType.OPENCTI_CUSTOM_DASHBOARD]:
    ServiceDefinitionIdentifier.OpenctiCustomDashboards,
  [ShareableResourceType.OPENCTI_CUSTOM_VIEW]:
    ServiceDefinitionIdentifier.OpenctiCustomViews,
  [ShareableResourceType.OPENAEV_SCENARIO]:
    ServiceDefinitionIdentifier.OpenaevScenarios,
  [ShareableResourceType.OPENCTI_PLAYBOOK]:
    ServiceDefinitionIdentifier.OpenctiPlaybooks,
};

export const SHAREABLE_RESOURCE_SERVICE_SLUG_MAPPING: Record<
  ShareableResourceType,
  ServiceSlug
> = {
  [ShareableResourceType.OPENCTI_INTEGRATION]:
    ServiceSlug.OPEN_CTI_INTEGRATIONS,
  [ShareableResourceType.OPENCTI_CUSTOM_DASHBOARD]:
    ServiceSlug.OPEN_CTI_CUSTOM_DASHBOARDS,
  [ShareableResourceType.OPENAEV_SCENARIO]: ServiceSlug.OPEN_AEV_SCENARIOS,
  [ShareableResourceType.OPENCTI_PLAYBOOK]: ServiceSlug.OPEN_CTI_PLAYBOOKS,
  [ShareableResourceType.OPENCTI_CUSTOM_VIEW]:
    ServiceSlug.OPEN_CTI_CUSTOM_VIEWS,
};

export const isIntegrationItem = <
  T extends documentItem_fragment$data | PublicDocumentData,
>(
  resource: T
): resource is T & IntegrationFields => {
  return resource.type === ShareableResourceType.OPENCTI_INTEGRATION;
};

export const isConnectorResource = <
  T extends documentItem_fragment$data | PublicDocumentData,
>(
  resource: T
): resource is T & ConnectorFields => {
  return resource.__typename === 'Connector';
};
