scalar JSON
scalar Date
scalar Upload

enum FiligranProduct {
  opencti
  openaev
  xtmone
  xtmhub
}

enum FilterKey {
  label
  organization_id
  personal_space
  integration_type
  slug
  product_version
  manager_supported
  feed_url
  verified
  entity_type
  license_type
  solution_category
  object_type
  sector
  region
}

enum LogicalOperator {
  AND
  OR
}

input Filter {
  key: FilterKey!
  value: [String!]!
}

input LogicalFilterInput {
  leaf: Filter
  operator: LogicalOperator
  children: [LogicalFilterInput!]
}

type Success {
  success: Boolean!
}
